### PR TITLE
Fix #65 start adding solution exercise

### LINKED ISSUE #65: make check your understanding boxes with solutions
Idea (with @annefou ):
All exercise boxes that exist at the moment could become check your understanding boxes in the end of lessons with solutions added. 
Not to be done in class but in participants own time, therefore we need to offer solutions or at least a thought.

### PR DESCRIPTION
**Pull request by annefou**

### CODE REVIEW

**Comment by annefou** [comment]
I am not 100% sure about the answers and explanations are fully correct!

**Comment by bast** [comment]
I will review really soon ...

**Comment by bast** [comment]
3: Other risks: It may not be clear whether you can use and distribute (publish) the bugfixed code. For the repo owners it may not be clear whether they can use and distributed the bugfixed code.

6: Isn't the problem rather that the combined work would have to be licensed under GPL? I would say they can be combined but then the combination needs to be shared and cannot be closed.

8: Perhaps least attractive is GPL and AGPL. I think LGPL/MPL is more attractive since it localizes what needs to be shared. Most attractive: MIT, BSD, Apache.

**Comment by annefou** [comment]
Thanks.  Isn't GPL license a viral license? sor for 5, you may not need to re-license to GPL if you keep codes separated but to combine them you would need to adopt a GPL license. 
I must admit that I don't know GPL that well (except I need to avoid them...).

**Comment by bast** [comment]
GPL is a "viral" license so derivative work of GPL would be GPL or more open.

**Comment by annefou** [comment]
So for 6 can we still re-license under GPL or does it depend on the type of viral license we have for this additional piece of software?

**Comment by bast** [comment]
Yes, I think the answer would be that derivative work would need to be shared under this viral license (e.g. AGPL or GPL), unless the components are only plugins or libraries.

**Review by bast — APPROVED** [review]

**Pull request merged**
