### PR TITLE
Lesson redesign

### PR DESCRIPTION
**Pull request by bast**
Work in progress. Suggestions on the way are always welcome:
https://cicero.xyz/v3/remark/0.14.0/github.com/coderefinery/social-coding/radovan-lesson-redesign/talk.md/

### CODE REVIEW

**Comment by bast** [comment]
Un-WIPed. Still quite some work left but it's taking shape and in my opinion it could even be merged at this point to prune the list of issues.

**Comment by wikfeldt** [comment]
looks very good to me!

**Comment by bast** [comment]
Thanks! I will merge this now to see better what is left to do. I think it is definitely better than before.

**Comment by rkdarst** [comment]
I didn't have time to fully review last week, but I think it looks very good!

**Pull request merged**
