### PR TITLE
fix #60 add generation of webpages with sphinx

### LINKED ISSUE #60: Update workflow to show content instead of slides
Right now, the website shows still the slide set as lesson material.
Better would be to show the lesson material, sphinx style.
Slides should stay available within repository

### PR DESCRIPTION
**Pull request by annefou**
- also need to add github token to repo.

### CODE REVIEW

**Comment by annefou** [comment]
Should fix #60 (workflows were already introduced before so it only required to add sphinx).

**Comment by samumantha** [comment]
I do not know about the workflows, could @rkdarst or @bast please take a look? Thanks! :)

**Comment by bast** [comment]
We don't need to generate a token. And this workflow generates from a `main` branch but the default branch here is `master`. I recommend to change the default branch to `main`. Let me know if I can help with that.

**Comment by bast** [comment]
Sorry, correction:
- first this should be merged, then the default branch changed. Otherwise it closes this PR.

**Comment by annefou** [comment]
@bast I don't have right access to rename the master branch to main (well technically, I could by creating a new main branch and deleting the master branch). Maybe it is easier if someone with proper access can do it.

**Comment by bast** [comment]
Default branch renamed. And I also raised your permissions.

**Pull request merged**
