### PR TITLE
Small fixes (punctuation etc.)

### PR DESCRIPTION
**Pull request by matuskalas**
- punctuation
- typos
(mostly in the poll options)
- added link to the EU DB directive

### CODE REVIEW

**Comment by matuskalas** [comment]
@arockenberger @naoe-tatara 
I fixed a couple of typos and some punctuation, mostly in the options for the polls. Please review, many thanks! 😊

**Review by arockenberger — APPROVED** [review]
Looks good! Thanks for the improvement!

**Comment by naoe-tatara** [comment]
For some reason the PR-page cannot be shown, with HTTP error 406.

So I am sorry but I cannot implement the changes in the poll now.


I hope it will work soon or at least tomorrow morning so that I can be in time to reflect the changes.

?


Naoe

________________________________

**Comment by matuskalas** [comment]
> For some reason the PR-page cannot be shown, with HTTP error 406.

Oh no, a GitHub is having a problem 😧
Now it seems to work fine again, at least for me...

Thanks for your fast replies @arockenberger @naoe-tatara 🙏🏽

**Comment by naoe-tatara** [comment]
Thanks, I implemented all the changes to the Zoom poll now.
The problem was not at the GitHub, but it was caused by an extension that I installed during FAIR Data Stewardship course to show the headers (or basically machine-readable data structure).

**Pull request merged**
