### PR TITLE
content/licensing: make the two questions `discussion` instead of `exercise`

### PR DESCRIPTION
**Pull request by rkdarst**
- Matches their spirit more (and other pages have only discussions,
  not exercise blocks).
- They won't be in the exercise list, but anyway the other pages
  aren't there.
- The exercise list will then be empty (but actually I have a pending
  change that can allow us to put discussions there, so maybe we leave
  it for the time being?
- Review: consider the points above

### CODE REVIEW

**Comment by rkdarst** [comment]
with https://github.com/coderefinery/sphinx-lesson/pull/89 we can have the discussion questions in the exercise list, but I would need another sphinx release (this is very fast)

**Comment by bast** [comment]
Maybe we can leave it for the moment? Empty exercise page could look strange and at least for tomorrow we say in the detailed agenda that there won't be group exercises so hopefully it is not a problem for tomorrow.

**Comment by bast** [comment]
In a smaller workshop these could be group exercise. In a huge workshop as tomorrow they will be more of a discussion.

**Comment by rkdarst** [comment]
I'm now also prepared (with minimal work) to add the discussions to
the exercise list page - just tested.  Needs a quick sphinx-lesson
release but not hard.

... but leaving it for later is probably best, no need to make extra
work.

**Comment by bast** [comment]
OK convinced. Merging. I will now anyway go through entire lesson once more and clean up remaining rough edges.

**Pull request merged**
